version: 2

jobs:
    build:
        docker:
            - image: ubuntu
        steps:
            - checkout
            - run:
                name: verify
                command: bash scripts/ex0-verify.sh
